# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
name: Windows Build and Release (v2)
on:
  workflow_dispatch:

jobs:
  build:
    name: Windows Build
    runs-on: windows-2022
    env:
      CRAFT_TARGET: windows-msvc2022_64-cl
      CRAFT_MASTER_LOCATION: ${{ github.workspace }}\CraftMaster
      CRAFT_MASTER_CONFIG: ${{ github.workspace }}\craftmaster.ini

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Craft Master with Nextcloud Client Deps
        shell: pwsh
        run: |
          & cmd /C "git clone -q --depth=1 https://invent.kde.org/packaging/craftmaster.git ${{ env.CRAFT_MASTER_LOCATION }} 2>&1"
          
          function craft() {
              python "${{ env.CRAFT_MASTER_LOCATION }}\CraftMaster.py" --config "${{ env.CRAFT_MASTER_CONFIG }}" --target ${{ env.CRAFT_TARGET }} -c $args
              if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
          }
          
          craft --add-blueprint-repository "https://github.com/nextcloud/craft-blueprints-kde.git|stable-3.17|"
          craft --add-blueprint-repository "https://github.com/nextcloud/desktop-client-blueprints.git|stable-3.17|"
          craft craft
          craft --install-deps nextcloud-client

      - name: Install dependencies (Inkscape, WiX)
        shell: pwsh
        run: |
          choco install inkscape
          choco install wixtoolset

      - name: Setup PATH
        shell: pwsh
        run: |
          echo "${{ github.workspace }}\${{ env.CRAFT_TARGET }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Compile Client
        shell: pwsh
        run: |
          function craft() {
              python "${{ env.CRAFT_MASTER_LOCATION }}\CraftMaster.py" --config "${{ env.CRAFT_MASTER_CONFIG }}" --target ${{ env.CRAFT_TARGET }} -c $args
              if($LASTEXITCODE -ne 0) {exit $LASTEXITCODE}
          }
          craft --src-dir ${{ github.workspace }} nextcloud-client

      - name: Package MSI (WiX multilingual)
        shell: pwsh
        run: |
          $outDir = "${{ github.workspace }}\out"
          $binDir = "${{ github.workspace }}\${{ env.CRAFT_TARGET }}\bin"
          mkdir $outDir -Force

          # 拷贝运行时
          Copy-Item -Path $binDir\* -Destination $outDir -Recurse -Force

          # 创建 ZIP
          $zipPath = "${{ github.workspace }}\NextcloudDesktop.zip"
          if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
          Compress-Archive -Path "$outDir\*" -DestinationPath $zipPath

          # WiX 多语言打包
          $langs = @("en-us", "ja-jp", "zh-cn")
          foreach ($lang in $langs) {
            $msiPath = "${{ github.workspace }}\NextcloudDesktop-$lang.msi"

            # 假设你有 Installer/Product.wxs 文件
            candle -dLang=$lang -out obj\ Product.wxs
            light -ext WixUIExtension -cultures:$lang -out $msiPath obj\Product.wixobj
          }

          echo "ZIP_PATH=$zipPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            ${{ github.workspace }}\NextcloudDesktop.zip
            ${{ github.workspace }}\NextcloudDesktop-en-us.msi
            ${{ github.workspace }}\NextcloudDesktop-ja-jp.msi
            ${{ github.workspace }}\NextcloudDesktop-zh-cn.msi

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            NextcloudDesktop.zip
            NextcloudDesktop-en-us.msi
            NextcloudDesktop-ja-jp.msi
            NextcloudDesktop-zh-cn.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
